
steps:
- name: "docker-compose"
  args: ["up", "-d", "--build"]
- name: 'gcr.io/cloud-builders/docker'
  args: ['tag', 'iafrohack-backend:latest', 'gcr.io/iafrohack/iafrohack-backend:$COMMIT_SHA']
images: ['gcr.io/iafrohack/iafrohack-backend:$COMMIT_SHA']
