version: '3'
services:
    api:
      image: gcr.io/iafrohack/iafrohack-backend:latest
      build:
        context: .
        args:
         - http_proxy
         - https_proxy
         - no_proxy
      ports:
        - "80:5000"
      volumes:
        - .:/usr/src/app
        - /Users/jmugabe/.config/gcloud/iafrohack-firestore.json:/var/lib/iafrohack/.config/gcloud/iafrohack-firestore.json
      depends_on:
        - mongodb
      restart: always
    mongodb:
        image: mongo
