version: '3'
services:
    api:
      build:
        context: .
        args:
         - http_proxy
         - https_proxy
         - no_proxy
      ports:
        - "80:5000"
      volumes:
        - .:/usr/src/app
      depends_on:
        - mongodb
      restart: unless-stopped
    mongodb:
        image: mongo
